### ISSUE TITLE
Moving towards a single model factory

### ISSUE THREAD

**Issue by paolofraccaro** [IBM/terratorch#135]
**Is your feature request related to a problem? Please describe.**
It is suboptimal and probably not scalable to have many different "model factories" for each model or libraries. 

**Describe the solution you'd like**
It would be great to figure out a solution where we abstract away (probably through some wrapping) the different libraries to contribute a single model factory. This is probably not straightforward but it will considerably improve the UX for terratorch.

**Comment by paolofraccaro** [comment]
This makes sense to me. Let's try to think of this by allowing some flexibility in how we combine encoders withe decoders, especially for plugging in decoders this is important. 

The measures you propose seem sufficient to handle vast majority of cases. Passing functions to adapt encoder output to decoder input makes sense. I would extend this (maybe we can provide reshape transforms available as well) to adapt the output of a datamodule to encoder. 

Only question, do we do any check on the funxtions provided by the user? Thinking in case the code is submitted for execution somewhere else.

**Comment by CarlosGomes98** [comment]
> Only question, do we do any check on the funxtions provided by the user? Thinking in case the code is submitted for execution somewhere else.

This is a good point, however, the user can already execute arbitrary datasets / datamodules / models, and all of those can execute arbitrary code as long as the user has access to the codebase. Without access to the codebase, the most the user could do is point to some function defined or imported somewhere. We might want to think about how to restrict this, but this is not the only mechanism that would need to be considered.

**Comment by CarlosGomes98** [comment]
With this refactoring, it probably makes sense to do some refactoring on the tasks too. 

For instance, currently, they take the argument `aux_heads`, which should probably be passed directly to the factory - the task doesn't need this information

**Comment by Joao-L-S-Almeida** [comment]
@CarlosGomes98 already did and deep and thorough evaluation about the issue, so I have just a few points to add (and maybe summarize what was exposed). 
- Our current decoder registry is a simple function which gets the corresponding class from a specific module (where all the possible decoder are pre-imported). Do you suggest to have a similar mechanism for the backbones, @CarlosGomes98 I agree that it would facilitate the instantiation and creation of new built-in backbones. We could even create a a kind of try-except constructor to search using timm and our inner registry. 

- The main problem with an universal class is that it aims to connect any pair (encoder, decoder) from any source and it is a non-trivial task, since the outputs produced by a particular encoder could be incompatible with the decoder chosen for it. 
I  believe (and I understand Carlos agrees with it) that more complex and non-usual combinations will require a better control from the user and, in this way, the user should use the programmatic interface for a better experience.

- In anyway, I believe we also could create an automatic solution, since it is relatively easy to categorize the possible kinds of "encoder outputs" and "decoder inputs" and create an intermediary compatibility layer. This layer could even inform the user about the modifications being carried out and about some eventual incompatibility that hinders its choice.
