### ISSUE TITLE
Why the preference for downloading geobench from GitHub

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/terratorch#202]
Why the preference for downloading geobench from GitHub ? Is it essential ? I have observed issues with PyPI when installing in this way (which have me obligated to recommend the installation from tarballs for `wxc`).

_Originally posted by @Joao-L-S-Almeida in https://github.com/IBM/terratorch/pull/186#discussion_r1815004148_

**Comment by daniszw** [comment]
Do we actually need this dependence? I didn't find any reference to it, but I may have missed something.
I'm asking because I'm facing issues related to the strict dependencies `geobench` has forced for `pandas` and `seaborn`. It actually requires pretty old versions of both (`^1.5.3`, `^0.12.2`, respectively) but there's nothing on `matplotlib`, which results in bugs due to version conflicts as you might have a more recent `matplotlib` version. I must say I've only seen these issues for plotting using `pandas` plot and `seaborn` plot.

**Comment by Joao-L-S-Almeida** [comment]
In fact, it isn't explicitly imported in any module. I'm not sure if @PedroConrado is still using it for some purpose. 
In any case, as it is currently [optionally installed](https://github.com/IBM/terratorch/blob/01125280eecd34f7ee9fbeae03b8d4804e37cef5/pyproject.toml#L72) , it shouldn't interfere in the normal installation.

**Comment by daniszw** [comment]
Nice that is currently optional, but I think it is worth checking anyway if we actually need that dependence somehow (maybe there’s something on downloading the datasets?), because I don’t think it is good to have the pandas version fixed to something from almost 2 years ago.

**Comment by Joao-L-S-Almeida** [comment]
I agree.

**Comment by PedroConrado** [comment]
The Geobench package is not being used for anything that Im currently developing.
