### ISSUE TITLE
Clarify differences between the input config file to terratorch training

### ISSUE THREAD

**Issue by romeokienzler** [IBM/terratorch#82]
Clarify differences between the input config file to terratorch training and then 2 config files returned by terratorch. Now, we have 3 config files. Which one is most suitable for inference?

**Comment by Joao-L-S-Almeida** [comment]
This [PR](https://github.com/IBM/terratorch/pull/58) tries to address this issue. 
The input file will be a subset of the outputted one, but this last has more verbose information, since it stores default choices for some of the classes.

**Comment by romeokienzler** [comment]
@CarlosGomes98 to review PR

**Comment by CarlosGomes98** [comment]
From my understanding of the issue, this is what I would say:

1. After the input config file is parsed by LightningCLI, it has a dictionary with all the settings for the run. By default, it takes this and writes them in a YAML config file in the output log directory. This is useful not only to be able to replicate that experiment, but also from a debugging/transparency standpoint, to be able to understand exactly the parameters which are being passed to the training.
2. The second config file produced is intended for inference only / deployment scenarios, where a few keys are removed from the config file. Instead of being generated automatically, it might make more sense to have a script that does this.
3. If we wish to, we can also have a `cp` operation where the input config file is also exactly replicated (e.g. this would preserve the order, as well as comments). But I see this as potentially confusing...

**Comment by romeokienzler** [comment]
@Michal-Muszynski is #109 fixing this?
